-- Add new bot states to the enum
ALTER TYPE bot_state ADD VALUE 'AWAITING_CUSTOM_CITY';
ALTER TYPE bot_state ADD VALUE 'AWAITING_CUSTOM_PRICE_MIN';
ALTER TYPE bot_state ADD VALUE 'AWAITING_CUSTOM_PRICE_MAX';
ALTER TYPE bot_state ADD VALUE 'VIEWING_RESULTS';