-- Admin posting states
ALTER TYPE bot_state ADD VALUE 'AWAITING_LISTING_TYPE';
ALTER TYPE bot_state ADD VALUE 'AWAITING_PRICE';
ALTER TYPE bot_state ADD VALUE 'AWAITING_CITY_FOR_POSTING';
ALTER TYPE bot_state ADD VALUE 'AWAITING_ROOMS';
ALTER TYPE bot_state ADD VALUE 'AWAITING_PHONE';
ALTER TYPE bot_state ADD VALUE 'AWAITING_DISTRICT';
ALTER TYPE bot_state ADD VALUE 'AWAITING_FLOOR';
ALTER TYPE bot_state ADD VALUE 'AWAITING_TOTAL_FLOORS';
ALTER TYPE bot_state ADD VALUE 'AWAITING_BUILDING_TYPE';
ALTER TYPE bot_state ADD VALUE 'AWAITING_CONDITION';
ALTER TYPE bot_state ADD VALUE 'AWAITING_CONFIRMATION';
ALTER TYPE bot_state ADD VALUE 'AWAITING_CHANNEL_SELECTION';